---
# Main playbook which runs all other playbooks
- name: Run all playbooks
  hosts: all
  remote_user: root
  vars_files:
    - ./site.vars

# All nodes
- import_playbook: ./playbooks/generic/site.yml
# Web nodes
- import_playbook: ./playbooks/webserver/site.yml

# Host specific tasks
- import_playbook: ./playbooks/host_specific/site.yml
