---
# Sets up the new ansible user and disables password login
- name: add a new user named ansible
  user:
      name: ansible
      shell: /bin/bash
      # If using a password file swap the commented out portions for 'password'
      # password: "{{lookup('file', '../../.secrets/ansible-pass.crypt')}}"
      password: "{{lookup('password', '/dev/null length=47 chars=ascii_letters') | password_hash('sha512')}}"
      update_password: on_create
      # Interestingly enough pulling from /dev/random is a permission denied error
      # Most of the PRs on github on ansible also suggest using /dev/null.
      # Will need to research more into this later

- name: Add ansible user to sudoers
  copy:
      dest: "/etc/sudoers.d/ansible"
      content: "ansible ALL=(ALL) NOPASSWD: ALL"

- name: Drop in SSH key
  authorized_key:
      user=ansible
      key="{{lookup('file', '../../.secrets/ansible_key.pub')}}"
      state=present
